# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-memory-bank" do
  desc "CLI tool to install GitHub Copilot Memory Bank templates"
  homepage "https://github.com/drewpayment/gh-memory-bank"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gh-memory-bank"

  on_macos do
    url "https://github.com/drewpayment/gh-memory-bank/releases/download/v0.0.3/gh-memory-bank_0.0.3_darwin_all.tar.gz"
    sha256 "b22c7204f4a62493706f9314970e1c73c9b12888f904a582794ce15e029e7ec9"
  end

  on_linux do
    on_intel do
      url "https://github.com/drewpayment/gh-memory-bank/releases/download/v0.0.3/gh-memory-bank_0.0.3_linux_amd64.tar.gz"
      sha256 "cf91283847ad43a4aacbafd090c951c64f8d723482959568b748a2dba94a880e"
    end
    on_arm do
      url "https://github.com/drewpayment/gh-memory-bank/releases/download/v0.0.3/gh-memory-bank_0.0.3_linux_arm64.tar.gz"
      sha256 "b1b6981611d9e238bf9369f6581fe655a41f1a13d7f4fa97644d2f7f01ed2456"
    end
  end

  # No zap stanza required
end
